
(require 'key-combo)
(key-combo-mode 1)
(key-combo-define-global (kbd "=") '(" = " " == " " === " ))
(key-combo-define-global (kbd ">") '(" > " " >> "))
(key-combo-define-global (kbd "<") '(" < " " << "))
(key-combo-define-global (kbd "<=") '(" <= "))
(key-combo-define-global (kbd ">=") '(" >= "))
(key-combo-define-global (kbd "!") '(" ! "))
(key-combo-define-global (kbd "!=") '(" != "))
(key-combo-define-global (kbd ",") '(", "))
